# Generated by Django 5.0.7 on 2024-09-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_of_departure', models.CharField(max_length=500)),
                ('delivery_city', models.CharField(max_length=500)),
                ('total_weight', models.FloatField()),
                ('dimension', models.CharField(max_length=500)),
                ('your_name', models.CharField(max_length=500)),
                ('your_email', models.EmailField(max_length=500)),
                ('phone', models.IntegerField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
