# Generated by Django 5.0.7 on 2024-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_a_quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
